# .circleci/config.yml
version: 2.1
on: 
   pull_request:
   push:
     branches:
     - master
     - develop
     
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: node --version
